/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 25.2 and Signal Processing Toolbox 25.2.
 * Generated on: 03-Mar-2026 13:31:26
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 99
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /usr/local/MATLAB/R2025b/extern/include/tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int numTaps = 100;
const int16_t hp22k[100] = {
     -544,    -98,   -106,   -115,   -124,   -134,   -143,   -153,   -163,
     -174,   -184,   -195,   -206,   -217,   -228,   -239,   -250,   -262,
     -273,   -285,   -296,   -307,   -318,   -329,   -340,   -351,   -362,
     -372,   -382,   -392,   -401,   -411,   -419,   -428,   -436,   -444,
     -451,   -458,   -464,   -470,   -475,   -480,   -484,   -488,   -491,
     -494,   -496,   -497,   -498,  32269,   -498,   -497,   -496,   -494,
     -491,   -488,   -484,   -480,   -475,   -470,   -464,   -458,   -451,
     -444,   -436,   -428,   -419,   -411,   -401,   -392,   -382,   -372,
     -362,   -351,   -340,   -329,   -318,   -307,   -296,   -285,   -273,
     -262,   -250,   -239,   -228,   -217,   -206,   -195,   -184,   -174,
     -163,   -153,   -143,   -134,   -124,   -115,   -106,    -98,   -544,
        0
};
