/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 25.2 and Signal Processing Toolbox 25.2.
 * Generated on: 03-Mar-2026 13:13:13
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 37
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /usr/local/MATLAB/R2025b/extern/include/tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int numTaps = 38;
const int16_t hp8k[38] = {
     -608,   -302,   -371,   -445,   -524,   -606,   -690,   -776,   -860,
     -943,  -1022,  -1095,  -1162,  -1222,  -1273,  -1313,  -1343,  -1361,
    31402,  -1361,  -1343,  -1313,  -1273,  -1222,  -1162,  -1095,  -1022,
     -943,   -860,   -776,   -690,   -606,   -524,   -445,   -371,   -302,
     -608,      0
};
