/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 25.2 and Signal Processing Toolbox 25.2.
 * Generated on: 03-Mar-2026 13:00:53
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 73
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /usr/local/MATLAB/R2025b/extern/include/tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
#ifndef LP44K_H
#define LP44K_H

#include <stdint.h>
#include "arm_math.h"
 
const int lp44k_taps = 74;
const q15_t lp44k[74] = {
     -501,    178,    215,    269,    319,    342,    324,    258,    147,
        7,   -139,   -261,   -332,   -332,   -253,   -104,     90,    293,
      459,    546,    523,    376,    118,   -213,   -559,   -845,   -997,
     -949,   -661,   -126,    628,   1533,   2495,   3404,   4149,   4639,
     4809,   4639,   4149,   3404,   2495,   1533,    628,   -126,   -661,
     -949,   -997,   -845,   -559,   -213,    118,    376,    523,    546,
      459,    293,     90,   -104,   -253,   -332,   -332,   -261,   -139,
        7,    147,    258,    324,    342,    319,    269,    215,    178,
     -501,      0
};

#endif
