/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 25.2 and Signal Processing Toolbox 25.2.
 * Generated on: 03-Mar-2026 13:32:52
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 195
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /usr/local/MATLAB/R2025b/extern/include/tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
#ifndef HP44K_H
#define HP44K_H

#include <stdint.h>
#include "arm_math.h"

const int hp44k_taps = 196;
const q15_t hp44k[196] = {
     -543,    -48,    -50,    -53,    -55,    -57,    -59,    -62,    -64,
      -66,    -69,    -71,    -74,    -76,    -79,    -81,    -84,    -86,
      -89,    -92,    -94,    -97,   -100,   -102,   -105,   -108,   -111,
     -114,   -117,   -119,   -122,   -125,   -128,   -131,   -133,   -136,
     -139,   -142,   -145,   -148,   -151,   -153,   -156,   -159,   -162,
     -165,   -167,   -170,   -173,   -176,   -178,   -181,   -184,   -186,
     -189,   -191,   -194,   -196,   -199,   -201,   -203,   -206,   -208,
     -210,   -212,   -214,   -216,   -218,   -220,   -222,   -224,   -226,
     -228,   -229,   -231,   -233,   -234,   -236,   -237,   -238,   -240,
     -241,   -242,   -243,   -244,   -245,   -246,   -246,   -247,   -248,
     -248,   -249,   -249,   -249,   -250,   -250,   -250,  32518,   -250,
     -250,   -250,   -249,   -249,   -249,   -248,   -248,   -247,   -246,
     -246,   -245,   -244,   -243,   -242,   -241,   -240,   -238,   -237,
     -236,   -234,   -233,   -231,   -229,   -228,   -226,   -224,   -222,
     -220,   -218,   -216,   -214,   -212,   -210,   -208,   -206,   -203,
     -201,   -199,   -196,   -194,   -191,   -189,   -186,   -184,   -181,
     -178,   -176,   -173,   -170,   -167,   -165,   -162,   -159,   -156,
     -153,   -151,   -148,   -145,   -142,   -139,   -136,   -133,   -131,
     -128,   -125,   -122,   -119,   -117,   -114,   -111,   -108,   -105,
     -102,   -100,    -97,    -94,    -92,    -89,    -86,    -84,    -81,
      -79,    -76,    -74,    -71,    -69,    -66,    -64,    -62,    -59,
      -57,    -55,    -53,    -50,    -48,   -543,      0
};

#endif
