/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 25.2 and Signal Processing Toolbox 25.2.
 * Generated on: 13-Nov-2025 15:03:38
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 16
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /usr/local/MATLAB/R2025b/extern/include/tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
const int numTaps = 16;
const real32_T firCoeffsQ15[16] = {
   -0.01434766315, -0.04392229393,   0.0464826934, -0.04859878123,  0.03185196966,
    0.01926242188,  -0.1377990693,    0.610089004,    0.610089004,  -0.1377990693,
    0.01926242188,  0.03185196966, -0.04859878123,   0.0464826934, -0.04392229393,
   -0.01434766315
};
