/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 25.2 and Signal Processing Toolbox 25.2.
 * Generated on: 12-Nov-2025 21:01:36
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 31
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /usr/local/MATLAB/R2025b/extern/include/tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int numTaps = 31;
const int16_T firCoeffsQ15[31] = {
      125,   -954,   -685,     86,    718,    272,   -792,   -874,    524,
     1590,    313,  -2274,  -2257,   2766,   9995,  13439,   9995,   2766,
    -2257,  -2274,    313,   1590,    524,   -874,   -792,    272,    718,
       86,   -685,   -954,    125
};
