/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 25.2 and Signal Processing Toolbox 25.2.
 * Generated on: 03-Mar-2026 12:59:45
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 43
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /usr/local/MATLAB/R2025b/extern/include/tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int numTaps = 44;
const int16_t lp22k[44] = {
      367,   -486,   -601,   -545,   -199,    269,    517,    311,   -243,
     -710,   -637,     47,    880,   1133,    385,  -1021,  -2025,  -1460,
     1115,   4953,   8397,   9776,   8397,   4953,   1115,  -1460,  -2025,
    -1021,    385,   1133,    880,     47,   -637,   -710,   -243,    311,
      517,    269,   -199,   -545,   -601,   -486,    367,      0
};
