/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 25.2 and Signal Processing Toolbox 25.2.
 * Generated on: 12-Nov-2025 21:02:13
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 85
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /usr/local/MATLAB/R2025b/extern/include/tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int numTaps = 85;
const int16_T firCoeffsQ15[85] = {
      468,   -214,   -233,   -268,   -298,   -304,   -273,   -204,   -101,
       18,    133,    219,    257,    236,    155,     27,   -122,   -260,
     -355,   -379,   -319,   -177,     23,    245,    440,    560,    566,
      442,    193,   -145,   -511,   -827,  -1012,   -996,   -730,   -203,
      557,   1483,   2477,   3420,   4198,   4710,   4888,   4710,   4198,
     3420,   2477,   1483,    557,   -203,   -730,   -996,  -1012,   -827,
     -511,   -145,    193,    442,    566,    560,    440,    245,     23,
     -177,   -319,   -379,   -355,   -260,   -122,     27,    155,    236,
      257,    219,    133,     18,   -101,   -204,   -273,   -304,   -298,
     -268,   -233,   -214,    468
};
