/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 25.2 and Signal Processing Toolbox 25.2.
 * Generated on: 03-Mar-2026 13:04:30
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 92
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /usr/local/MATLAB/R2025b/extern/include/tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
const int numTaps = 92;
const int16_t lp48k[92] = {
      458,   -242,   -241,   -260,   -278,   -281,   -258,   -207,   -128,
      -31,     70,    158,    219,    239,    212,    139,     32,    -94,
     -214,   -305,   -347,   -327,   -241,    -98,     81,    266,    421,
      515,    522,    426,    232,    -37,   -344,   -636,   -855,   -947,
     -866,   -588,   -110,    544,   1323,   2157,   2964,   3662,   4174,
     4446,   4446,   4174,   3662,   2964,   2157,   1323,    544,   -110,
     -588,   -866,   -947,   -855,   -636,   -344,    -37,    232,    426,
      522,    515,    421,    266,     81,    -98,   -241,   -327,   -347,
     -305,   -214,    -94,     32,    139,    212,    239,    219,    158,
       70,    -31,   -128,   -207,   -258,   -281,   -278,   -260,   -241,
     -242,    458
};
