/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 25.2 and Signal Processing Toolbox 25.2.
 * Generated on: 03-Mar-2026 13:13:51
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 73
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /usr/local/MATLAB/R2025b/extern/include/tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
#ifndef HP16K_H
#define HP16K_H

#include <stdint.h>
#include "arm_math.h"


const int hp16k_taps = 74;
const q15_t hp16k[74] = {
     -540,   -135,   -151,   -168,   -185,   -203,   -222,   -242,   -262,
     -282,   -303,   -324,   -345,   -367,   -388,   -409,   -430,   -451,
     -471,   -491,   -511,   -530,   -548,   -565,   -582,   -597,   -611,
     -625,   -637,   -647,   -657,   -665,   -671,   -677,   -681,   -683,
    32085,   -683,   -681,   -677,   -671,   -665,   -657,   -647,   -637,
     -625,   -611,   -597,   -582,   -565,   -548,   -530,   -511,   -491,
     -471,   -451,   -430,   -409,   -388,   -367,   -345,   -324,   -303,
     -282,   -262,   -242,   -222,   -203,   -185,   -168,   -151,   -135,
     -540,      0
};

#endif
