/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 25.2 and Signal Processing Toolbox 25.2.
 * Generated on: 03-Mar-2026 13:34:54
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 213
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /usr/local/MATLAB/R2025b/extern/include/tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */
#ifndef HP48K_H
#define HP48K_H

#include <stdint.h>
#include "arm_math.h"
 
const int hp48k_taps = 214;
const q15_t hp48k[214] = {
     -537,    -44,    -46,    -47,    -49,    -51,    -53,    -55,    -57,
      -59,    -61,    -63,    -65,    -67,    -69,    -71,    -73,    -75,
      -78,    -80,    -82,    -84,    -87,    -89,    -91,    -93,    -96,
      -98,   -100,   -103,   -105,   -107,   -110,   -112,   -115,   -117,
     -120,   -122,   -124,   -127,   -129,   -131,   -134,   -136,   -139,
     -141,   -143,   -146,   -148,   -150,   -153,   -155,   -157,   -160,
     -162,   -164,   -166,   -168,   -171,   -173,   -175,   -177,   -179,
     -181,   -183,   -185,   -187,   -189,   -191,   -193,   -195,   -196,
     -198,   -200,   -201,   -203,   -205,   -206,   -208,   -209,   -210,
     -212,   -213,   -214,   -216,   -217,   -218,   -219,   -220,   -221,
     -222,   -223,   -224,   -224,   -225,   -226,   -226,   -227,   -227,
     -228,   -228,   -228,   -229,   -229,   -229,   -229,  32539,   -229,
     -229,   -229,   -229,   -228,   -228,   -228,   -227,   -227,   -226,
     -226,   -225,   -224,   -224,   -223,   -222,   -221,   -220,   -219,
     -218,   -217,   -216,   -214,   -213,   -212,   -210,   -209,   -208,
     -206,   -205,   -203,   -201,   -200,   -198,   -196,   -195,   -193,
     -191,   -189,   -187,   -185,   -183,   -181,   -179,   -177,   -175,
     -173,   -171,   -168,   -166,   -164,   -162,   -160,   -157,   -155,
     -153,   -150,   -148,   -146,   -143,   -141,   -139,   -136,   -134,
     -131,   -129,   -127,   -124,   -122,   -120,   -117,   -115,   -112,
     -110,   -107,   -105,   -103,   -100,    -98,    -96,    -93,    -91,
      -89,    -87,    -84,    -82,    -80,    -78,    -75,    -73,    -71,
      -69,    -67,    -65,    -63,    -61,    -59,    -57,    -55,    -53,
      -51,    -49,    -47,    -46,    -44,   -537,      0
};

#endif
